GC_plot <- function(seq,size,type,filepath) {
  library(Biostrings)
  library(ggplot2)
  seq <- DNAString(seq)
  type<-strsplit(type,"")[[1]]
  GC <-rowSums(letterFrequencyInSlidingView(seq, size, type)) / size
  GC.data <- data.frame(x = c(1:(nchar(seq) - (size-1))), y = GC)
  p <-
    ggplot(data = GC.data, aes(x = x, y = y)) + geom_line(color = "red") + theme_bw() +
    theme(panel.grid = element_blank())+theme(plot.margin=unit(rep(3,4),'lines'))
  p<- p + xlab("Sequence 1") + ylab("Sequence 2")+ theme(axis.text.x = element_text(size=12,color = "black"),axis.text.y = element_text(size=12,color = "black"))+
    scale_x_continuous(n.breaks=8)
  png(file = paste0(filepath,"//","GC content.png"),width = 480*3,height = 480*2,res = 72*2)
  print(p)
  dev.off()
  Full_length<-length(seq)
  A_count<-letterFrequency(seq,"A")
  A_percent<-paste0(round(A_count/Full_length*100,2),"%")
  T_count<-letterFrequency(seq,"T")
  T_percent<-paste0(round(T_count/Full_length*100,2),"%")
  G_count<-letterFrequency(seq,"G")
  G_percent<-paste0(round(G_count/Full_length*100,2),"%")
  C_count<-letterFrequency(seq,"C")
  C_percent<-paste0(round(C_count/Full_length*100,2),"%")
  Count<-data.frame(A=A_count,T=T_count,G=G_count,C=C_count)
  return(Count)
}

# seq<-"TTACTTGGGTGTGGAGGCATGTGCCTATAATCCAAGGTACTCAGGAGGCTGAGGCATGAGAATTGCTTGAACCCGGGAGGTAGAGGTTGCAGTGAGCTGAGATTATGCCACTGCACTCCAGCCTGGATGACAGAGTGAGGCTCTGTCTCAAAAAAAAAAAAAAAAAAAAAAAAGAAGTAGAATCATATGGTAATTCTGTGTTTAACTTTTTGAGGAACGCCAGACTCTTCCAAACCACTGCCCTGTGTTACATTCCCAGTAGCAATGTGTTCAGTTGCTTCACATCTTTCCCAACGCTTTTGATTTTCCTCTTTATTTTTCATTGAATCTAATCCTAGTGGGTATGAAGTATCTTACTGTGTTTTGATTTGCATTTCTCTAATGAATAATGATGTTGAGCATATTTTCATGTGCTTATGGGTCATTTGTAAACTTTTAGAGAAATGTCTGTTCCAATCTTTTATCCGTTTTAAAAATTGGATTGTCTTTTTGTTGTTGAGGTATAAGATTTCTTTCTATGTTCTAGATATTAGATGCTTAACAGATAAGCAGGAGAATCGCCTGAACCCGGGAGGCAGAGGCTGCAGTGAGCGGAGATTGTACCGCTGCCCTCCAGCCTGGGCGACAGAGGAGGGAGACTGTCTGAAACAAACAACAACAACAACAACAAGATGAAAATAATACGGCAAATACTGTTCTTGACTTTTACTGTATCGAGTGAGAACTGTAAGGCTTAGAACAGCATGTGGTGGACTGTAATGATTCTATTTGTTTGCTTCTTATCCCTTTGCTTCACCCAGAAAAGGATTATAGCAGTCTTTGTGACAAGCAACCGATAGGAAGACGTCTCTTCAGGCAGTTCTGTGATACCAAACCCACTCTAAAGAGGCACATTGAATTCTTGGATGCAGTGGTGAGCAGTTTATCTCCATATTGAGCAACCACCCAATCTTATGCTTTTGAAAATGTAAAAACTTGGCCAGGCGCAGTAGCTCATGCTGTAATCCCAGCATTTTGGAAGGCTGAGGCGGGCGGATCATGAGGTCAGGAGATCGAGACCATCCTGACCAACACAGTGAAACCCGTCTCTACTAAAATACAAAAAGTTAGCCGGGCGTGGTGGCGCGTGCCTGTAGTCCCAGCTACTTGGGAGGCTGAGGCAGGGGAATCACTTGAACCAGGAGGCGGAGGTTGCAGTGAGCCGAGATCGCACCACTGCCTTCCAGCCTGGGCGACAGAGCAAGACTCCGTCTCAAAAAAAAAGAAAATGTAAAAACTAGACCTGGGCAATGATGTAGGAGTGGAGGGACTGGTTGTCTTGGTGTCATATTATCTTATTAGGACAGAAATCCCTTTAGTCTGAAGTGGTATTTTGTGTAGAATTACGTCTCAAGTGTTGGAGAATCACATGTAGTCATTGAATGACTTTGAAACTTGAGGCTTGAATTGTATGAAGATGACAAACTAATTAAGATGATAATGCTTTTTTTATTTTTTATTTTTTTGAAATGGAGTCTCTCTCTGTCTCCCAGGCTGGACTGCAGTGGCATGATCTTGGCTTACTGCAACCTCCGCCTCCTGGGTTCAAGCAATTCTTCTGCCTCAGCCTTGTGATCCACCTGCCTTGGCCCCCCAAAGTGCTGGGATTACAGGCATAAGCCACTGTGCCCGGCTCTAAGATGATAGTGCTTGTTCGGCTACCAGAAAAGTGTC"
# size<-30
# type<-c("GC")
# AA<-GC_plot(seq,size,type)
